name: Build and test wheels

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]
    branches: [master]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build and test wheels
        uses: pypa/cibuildwheel@v2.19.2
        with:
          package-dir: .
          output-dir: dist
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          path: dist/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: pypi

    # upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
